### PR TITLE
Update compiler version

### PR DESCRIPTION
**Pull request by cartermp**
@enricosada This updates the compiler to the latest build we have on NuGet.

/cc @KevinRansom

### CODE REVIEW

**Comment by enricosada** [comment]
@cartermp the `System.ValueTuple` package version required by compiler package is not published on nuget.org yet.
we should use [v4.0.0-rc3-24212-01](https://www.nuget.org/packages/System.ValueTuple/4.0.0-rc3-24212-01) in visualfsharp. is that version ok too? i'll open an issue in visualfsharp repo about that.

with a clean build (and no `System.ValueTuple` on the nuget cache)

running `build.cmd`

```
error: Unable to resolve 'System.ValueTuple (>= 4.0.1-beta-24405-03)' for '.NETCoreApp,Version=v1.0'.
```


as note: it doesnt matter if it's specified to use only the nuget.org as source feed, because if nuget find the package in the local cache (on windows `C:\Users\%USER%\.nuget\packages`) the package restore complete successufully.
if you can enable appveyor or jenkins in this repo, and run `build.cmd` it's easier to see the error and build/pr are safer

**Comment by cartermp** [comment]
@enricosada looks like it's already getting used: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Compiler/project.json#L22

@KevinRansom would we need to just publish a new build of the comiler?

**Comment by KevinRansom** [comment]
@cartermp @enricosada 
It's a bug in the nuspec file ... I will fix it and republish today
````
project.json
{
  "dependencies": {
   ...
    "System.ValueTuple": "4.0.0-rc3-24212-01",
  },

nuspec:
        <dependencies>
            <group targetFramework=".NETStandard1.6">
                ....
                <dependency id="System.ValueTuple" version="4.0.1-beta-24405-03" />
                ...
            </group>
        </dependencies>
````

Kevin

**Comment by KevinRansom** [comment]
@enricosada @cartermp 
Done:   
       https://www.nuget.org/packages/Microsoft.FSharp.Compiler.Host.netcore/1.0.0-alpha-160831

**Comment by cartermp** [comment]
Updated to latest.

**Comment by enricosada** [comment]
nice, let me try to build some libraries (suave, argu) to test the new compiler!

**Pull request merged**
