### PR TITLE
add imports required for Roslyn project system.

### PR DESCRIPTION
**Pull request by enricosada**
ref https://github.com/dotnet/netcorecli-fsc/issues/106

### CODE REVIEW

**Comment by enricosada** [comment]
Ok, seems to work.

image

@srivatsn @brettfo So i added built packages in https://www.myget.org/feed/Packages/netcorecli-fsc-roslyn

There are two [FSharp.NET.Sdk packages](https://www.myget.org/feed/netcorecli-fsc-roslyn/package/nuget/FSharp.NET.Sdk):

- `v1.0.4-bundled-0001` contains the `Sdk` dir who need to be bundled (for VS in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\FSharp.NET.Sdk\Sdk` ) but can be used by `dotnet/cli` and `mono` too
- `v1.0.4-rc3-0001` is the normal nupkg used in `fsproj` and restored as `PackageReference`

I added https://github.com/enricosada/DotnetNewFsprojTestingSamples/tree/roslyn-ps with two samples ready to use (just open the sln, like `sample1/sample1.sln`)

/cc @KevinRansom @cartermp

**Comment by enricosada** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by enricosada** [comment]
I resetted and merged with ff, to have a `master` history with no branches.
@cartermp np, is just a personal preference, but next time please use `Rebase and merge` button 😄

**Comment by cartermp** [comment]
Whoops, sorry!

**Pull request merged**
