### PR TITLE
bump FSharp.Compiler.Tools to 4.1.2

### PR DESCRIPTION
**Pull request by enricosada**
ref #96

### CODE REVIEW

**Comment by enricosada** [comment]
@mmitche hi, i am trying to run `msbuild`, and in current build workers is not in `PATH`.
how can i add that? is ok if is only for windows workers.

**Comment by mmitche** [comment]
@enricosada It's not supposed to be on the path for these machines.  If you're looking for the VS version, then you should emulate the developer experience and launch the vs developer command line environment prior to starting the build in the CI file, or integrate that logic into your build script.  That ensures you get the version of VS you want.

**Comment by enricosada** [comment]
Thx @mmitche , need to think about what the best thing to do

> or integrate that logic into your build script

i fear pain maintaining env var to set,  so as last option.

> or you should emulate the developer experience and launch the vs developer command line environment prior to starting the build in the CI file

so running `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"` .

I think i need to steal from https://github.com/dotnet/roslyn-project-system/blob/adf311612a2531b4078500d711915610da2e7d45/netci.groovy#L20-L27 so.

@davkean may i ask what do you think is the best thing to do (or who to ask about it?):

- i'd like to run `msbuild,exe myconsole.fsproj /t:Build` (to test the f# sdk and projects works the same with msbuild.exe (.net full) like `dotnet msbuild  myconsole.fsproj /t:Build` )
- minimal conf if possible, best if just some env var (so i can add to Process.Start in tests)

**Comment by enricosada** [comment]
Adding also @livarcocc if you have some ideas about previous Q in https://github.com/dotnet/netcorecli-fsc/pull/100#issuecomment-290154839 about testing msbuild.exe (full) projects in test suite and CI

**Comment by enricosada** [comment]
As a note for everyone, locally already works ok, if i enter in VS cmd promt, so:

- `dotnet msbuild myapp.fsproj /t:Build`
- `msbuild.exe myapp.fsproj /t:Build`

works the same (the former using f# compiler netcore as `dotnet fsc.dll`, the latter using f# compiler net45 as `fsc.exe`). 
mono will follow in the same way

**Comment by enricosada** [comment]
Ok merging this.

CI doesnt enable msbuild host full (msbuild.exe) yet.

It's possibile to test it from command line (using VS Command Prompt)

```
set TEST_SUITE_MSBUILD_HOST_TYPES=MSBUILD
build
```

this will run both msbuild host Core (dotnet msbuild) and .NET Full (msbuild.exe)

**Pull request merged**
