### PR TITLE
Add job that targets the latest mono-devel

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@enricosada I have no idea whether I got the build commands right here or anything, but you can modify this PR branch.

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by enricosada** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by enricosada** [comment]
Thank A LOT @mmitche !

I'll modify the build script to take advantage of this specific build agent! thank a lot!

**Pull request merged**
