### PR TITLE
Add implicit defines for framework, configuration

### PR DESCRIPTION
**Pull request by neoeinstein**
Currently, the SDK does not automatically provide defined constants for the target framework (a regression from the beta). It also uses an old technique for defining the `DEBUG` constant.

This change uses the same means of providing these constants as C# and VB.Net. It _does not_ provide the `TRACE` constant, as C# and VB.Net do not provide these constants by default. If the `TRACE` constant is necessary, that needs to be defined by the end user.

### CODE REVIEW

**Comment by enricosada** [comment]
@dotnet-bot build Ubuntu16.04 x64 Debug Build please

**Comment by neoeinstein** [comment]
@dotnet-bot build Ubuntu16.04 x64 Debug Build please

**Comment by enricosada** [comment]
@dotnet-bot build this please

**Comment by enricosada** [comment]
issue with ci hook :D, let's wait

**Comment by neoeinstein** [comment]
Looks like problems downloading the SDK for Ubuntu:

```
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004771/dotnet-dev-ubuntu.16.10-x64.1.0.0-rc4-004771.tar.gz
```

**Comment by enricosada** [comment]
@dotnet-bot build Ubuntu16.04 x64 Debug Build please

**Comment by neoeinstein** [comment]
@enricosada Looks like Ubuntu behaved this time.

**Comment by enricosada** [comment]
Yes @neoeinstein .
i was just adding some test to this PR, to check

- configuration (RELEASE, DEBUG) ifdef
- target fw (NETSTANDARD1_6, NET451, NETCOREAPP)

pratically is just:

- create a testAssets project like [test/testAssets/TestAppWithRes](https://github.com/dotnet/netcorecli-fsc/tree/master/test/testAssets/TestAppWithRes), so a console app
- add a test like [this](https://github.com/dotnet/netcorecli-fsc/blob/2d2d75badce30421c356f189123f5d4e4e32bb02/test/dotnet-new.Tests/CommonScenarioTests.cs#L294-L318)
- in the Program.fs, under ifdef, just print the defines
- in the test, assert the console output

so is easier for regression (because is something we add, so test should be in this codebase)

**Comment by enricosada** [comment]
ok added tests, it should be ok, after that. merge :D

**Comment by enricosada** [comment]
added https://github.com/dotnet/netcorecli-fsc/issues/83 to track issue for changelog

**Comment by enricosada** [comment]
merged, thanks a lot @neoeinstein !

**Pull request merged**
